require File.dirname(File.basename(__FILE__)) + '/test/test_helper'
$:.unshift(File.expand_path(File.join(File.dirname(File.basename(__FILE__)), 'test')))

require 'tc_well_formed'
require 'tc_attributes'
require 'tc_document'
require 'tc_document_write'
require 'tc_dtd'
require 'tc_html_parser'
require 'tc_node'
require 'tc_node_attr'
require 'tc_node_cdata'
require 'tc_node_comment'
require 'tc_node_copy'
require 'tc_node_edit'
require 'tc_node_set'
require 'tc_node_set2'
require 'tc_node_text'
require 'tc_node_xlink'
require 'tc_ns'
require 'tc_parser'
require 'tc_parser_context'
require 'tc_reader'
require 'tc_relaxng'
# require 'tc_sax_parser' TODO (uncomment this once working on implementation)
require 'tc_schema'
require 'tc_traversal'
require 'tc_xinclude'
require 'tc_xpath'
require 'tc_xpointer'

# Compatibility
require 'tc_properties'
require 'tc_deprecated_require'